name: Test systems/frontend

on:
  push:
    branches:
      - development
      - master
    paths:
      - 'systems/frontend/**'
  pull_request:
    paths:
      - 'systems/frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: bash ./scripts/setup.sh
      - run: npx lerna exec --stream --concurrency 1 --scope='{backend,frontend}' -- bash scripts/ci/setup.sh
      - run: npx lerna exec --stream --concurrency 1 --scope=frontend -- bash scripts/ci/test.sh
